//SIDEBAR
export const SET_CONF_BACKGROUND_MAN = "SET_CONF_BACKGROUND_MAN";
export const SET_CONF_COLOR_MAN = "SET_CONF_COLOR_MAN";
export const SET_CONF_BACKGROUND_NEW = "SET_CONF_BACKGROUND_NEW";
export const SET_CONF_COLOR_NEW = "SET_CONF_COLOR_NEW";
export const SET_CONF_BACKGROUND_EDIT = "SET_CONF_BACKGROUND_EDIT";
export const SET_CONF_COLOR_EDIT = "SET_CONF_COLOR_EDIT";
export const SET_CONF_BACKGROUND_DIS = "SET_CONF_BACKGROUND_DIS";
export const SET_CONF_COLOR_DIS = "SET_CONF_COLOR_DIS";
export const SET_CONF_BACKGROUND_WAI = "SET_CONF_BACKGROUND_WAI";
export const SET_CONF_COLOR_WAI = "SET_CONF_COLOR_WAI";
//HTTP REQUESTS
export const GET_CATALOG = "GET_CATALOG";

export const GO_TO_NEW_PRODUCT = "GO_TO_NEW_PRODUCT";
export const GO_TO_EDIT_PRODUCT = "GO_TO_EDIT_PRODUCT";
export const GO_GET_OUT_PRODUCT = "GO_GET_OUT_PRODUCT";

//BUTTON EXIT
export const GO_GET_OUT_ENTERPRISE = "GO_GET_OUT_ENTERPRISE";
export const GO_GET_OUT_CATALOG = "GO_GET_OUT_CATALOG";
export const GO_GET_OUT_PURSHASE = "GO_GET_OUT_PURSHASE";
export const GO_SELECT_RECIPE = "GO_SELET_RECIPE";
export const GO_EDIT_RECIPE = "GO_EDIT_RECIPE";
export const GO_TO_LOCATION = "GO_TO_LOCATION";

//INSUMOS
export const GET_SUPPLIES = "GET_SUPPLIES";
export const DELETE_SUPPLIES = "DELETE_SUPPLIES";

//ORDENCOMPRAS
export const GET_ORDENCOMPRAS = "GET_ORDENCOMPRAS";
export const DELETE_ORDENCOMPRAS = "DELETE_ORDENCOMPRAS";

//ORDENCOMPRAS
export const GET_PROVEEDORES = "GET_PROVEEDORES";
export const DELETE_PROVEEDORES = "DELETE_PROVEEDORES";

//CENTER COST
export const GET_CENTER_COST = "GET_CENTER_COST";
export const DELETE_CENTER_COST = "DELETE_CENTER_COST";

//SUB RECETA
export const GET_SUB_RECETAS = "GET_SUB_RECETAS";
export const DELETE_SUB_RECETA = "DELETE_SUB_RECETA";

//RECETA
export const GET_RECETAS = "GET_RECETAS";
export const DELETE_RECETA = "DELETE_RECETA";


